#deveops - pipeline
name: $(date:yyyyMMdd)$(rev:rr)

stages:
  - stage: 'build'
    displayName: 'built-mvc'
    condition: succeeded()
    jobs:
      - job:
        condition: succeeded()
        displayName: 'build-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: UseDotNet@2
            displayName: 'dotnet installer'
            inputs:
              version: '2.2.401'
          - script: |
              dotnet build

trigger:
  - master
